version: '3'
services:
  client:
    build: .
    image: react-vod-client
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    command: yarn start
  client_prod:
    build: .
    image: react-vod-client-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    command: yarn build-serve
  ci_test:
    build: .
    image: react-vod-client
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      CI: 'true'
    command: yarn test
